[global]
error_log = /proc/self/fd/2

[www]
; if we send this to /proc/self/fd/1, it never appears
access.log = /proc/self/fd/2

user = appuser
group = appgroup

; Listen on all interfaces instead of just localhost
listen = 0.0.0.0:9000

pm = dynamic
pm.max_children = 20
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Ensure request termination on timeout of master process
pm.process_idle_timeout = 10s
request_terminate_timeout = 120s

; Ensure the FPM workers can still be reached, even if your backend of choice is down
ping.path = /ping

; Tweak memory limit
php_admin_value[memory_limit] = 128M